language:
  - objective-c
  - cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cd ..
script:
  - cd build
  - make
  - cd ..
  - rm -rf build
  - xcodebuild -configuration Release -project builds/ios/fayecpp.xcodeproj -target fayecpp -arch i386 -sdk iphonesimulator OBJROOT=obj SYMROOT=sym clean build
branches:
  only:
    - master