language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - mkdir ~/fayecpp-install-dir
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/fayecpp-install-dir -DCMAKE_BUILD_TYPE=Release ..
  - cd ..

script:
  - printenv
  - cd build
  - make
  - make install
  - cd ~
  - zip -r -9 $_system_name-$_system_version-$_system_arch-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.zip fayecpp-install-dir
  - curl --upload-file $_system_name-$_system_version-$_system_arch-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.zip --user nonamedemail@gmail.com:699e1f2a44ef ftp://node100.net2ftp.ru/public_http/fayecpp/
  - rm -rf build

branches:
  only:
    - master
    - dev
