language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install p7zip-full
  - mkdir ~/fayecpp-install-dir
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/fayecpp-install-dir -DCMAKE_BUILD_TYPE=Release ..
  - cd ..

script:
  - printenv
  - cd build
  - make
  - make install
  - cd ~
###  - zip -r -9 -x*bin* -x*cmake* -x*pkgconfig* -x*share* $_system_name-$_system_version-$_system_arch-$CXX-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.zip fayecpp-install-dir
  - 7z a -t7z -mx=9 -xr!cmake -xr!pkgconfig -xr!bin -xr!share $_system_name-$_system_version-$_system_arch-$CXX-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z fayecpp-install-dir
  - curl --upload-file $_system_name-$_system_version-$_system_arch-$CXX-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/
  - rm -rf build

branches:
  only:
    - master
    - dev
