language: cpp
os:
  - linux
###  - osx

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install p7zip-full
  - mkdir ~/fayecpp-install-dir
  - git submodule update --init --recursive
  - mkdir build
  - mkdir android-ndk32
  - mkdir android-ndk64
  - mkdir android-ndk-10c
  - cd android-ndk32
  - curl -o ndk32.tar.bz2 http://dl.google.com/android/ndk/android-ndk32-r10b-linux-x86_64.tar.bz2
  - tar xjf ndk32.tar.bz2
  - rm ndk32.tar.bz2
  - cd ../android-ndk64
  - curl -o ndk64.tar.bz2 http://dl.google.com/android/ndk/android-ndk64-r10b-linux-x86_64.tar.bz2
  - tar xjf ndk64.tar.bz2
  - rm ndk64.tar.bz2
  - cd ../android-ndk-10c
  - curl -o ndk.bin http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin
  - chmod a+x ndk.bin
  - 7z x ndk.bin >> 1.txt
  - rm ndk.bin
  - cd ..
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/fayecpp-install-dir -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER ..
  - cd ..

script:
  - printenv
  - cd build
  - make
  - make install
  - cd ..  
  - ./android-ndk32/android-ndk-r10b/ndk-build NDK_PROJECT_PATH=builds/android/
  - cp -r builds/android/libs android-ndk32/
  - rm -rf builds/android/libs
  - rm -rf builds/android/obj
  - mkdir android-ndk32/include
  - cp fayecpp.h android-ndk32/include/
  - rm -rf android-ndk32/android-ndk-r10b
  - 7z a -t7z -mx=9 android-ndk32-r10b-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z android-ndk32
  - rm -rf android-ndk32
  - curl --upload-file android-ndk32-r10b-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/  
  - ./android-ndk64/android-ndk-r10b/ndk-build NDK_PROJECT_PATH=builds/android/
  - cp -r builds/android/libs android-ndk64/
  - rm -rf builds/android/libs
  - rm -rf builds/android/obj
  - mkdir android-ndk64/include
  - cp fayecpp.h android-ndk64/include/
  - rm -rf android-ndk64/android-ndk-r10b
  - 7z a -t7z -mx=9 android-ndk64-r10b-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z android-ndk64
  - rm -rf android-ndk64
  - curl --upload-file android-ndk64-r10b-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/  
  - ./android-ndk-10c/android-ndk-r10c/ndk-build NDK_PROJECT_PATH=builds/android/
  - cp -r builds/android/libs android-ndk-10c/
  - rm -rf builds/android/libs
  - rm -rf builds/android/obj
  - mkdir android-ndk-10c/include
  - cp fayecpp.h android-ndk-10c/include/
  - rm -rf android-ndk-10c/android-ndk-r10c
  - 7z a -t7z -mx=9 android-ndk-r10c-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z android-ndk-10c
  - rm -rf android-ndk-10c
  - curl --upload-file android-ndk-r10c-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/
  - cd ~
###  - zip -r -9 -x*bin* -x*cmake* -x*pkgconfig* -x*share* $_system_name-$_system_version-$_system_arch-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.zip fayecpp-install-dir
  - 7z a -t7z -mx=9 -xr!cmake -xr!bin -xr!pkgconfig -xr!share $_system_name-$_system_version-$_system_arch-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z fayecpp-install-dir
  - curl --upload-file $_system_name-$_system_version-$_system_arch-$CC-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/

branches:
  only:
    - master
###    - dev
