language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cd ..
script:
  - cd build
  - make
  - cd ..
  - rm -rf build
branches:
  only:
    - master