language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get upgrade cmake
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cd ..
script:
  - cd build
  - make
  - cd ..
  - rm -rf build
branches:
  only:
    - master