version: 0.2.2.{build}

# branches to build
branches:
  only:
  - master
  - dev

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

configuration:
  - Release

# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cd c:\dev\FayeCpp
  - md fayecpp-install-dir
  - git submodule update --init --recursive
#  - cd libwebsockets
#  - git apply < ../libwebsockets_h.patch
#  - cd ../jansson
#  - git apply < ../jansson_msc_1900.patch
#  - cd .. 

build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-dir -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - cmake --build . --config Release
  - ctest

