version: 1.5.{build}

# branches to build
branches:
  only:
#  - master
  - dev
  
# Operating system (build VM template)
os: Windows Server 2012

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
#  - x64
#  - AnyCPU

configuration:
#  - Debug
  - Release
  
# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cinst 7zip.commandline -x86
  - cd c:\dev
  - cd c:\dev\FayeCpp
  - git submodule update --init --recursive
  
build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - md win-install
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\win-install -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -G"Visual Studio 11" ..
  - dir
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" FayeCpp.sln
#  - cd Release
#  - dir
  - cmd: cmake --build C:\dev\FayeCpp\build --target INSTALL
  - cd c:\dev\FayeCpp\win-install
  - dir
#  - cmd: 7za a -r -t7z c:\dev\release-x86-win32-windows-server-2012.7z c:\dev\FayeCpp\build
  - cmd: 7za a -tzip c:\dev\"%APPVEYOR_PROJECT_NAME%-%OS%-%PLATFORM%-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.zip" c:\dev\FayeCpp\build\Release
  - dir
  - curl --upload-file c:\dev\c:\dev\"%APPVEYOR_PROJECT_NAME%-%OS%-%PLATFORM%-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.zip" --user nonamedemail@gmail.com:699e1f2a44ef ftp://node100.net2ftp.ru


after_build:

test_script:
