version: 1.1.0.{build}

os: Visual Studio 2015

environment:
  matrix:
    - DEFAULT_MAT: "DEF"
      
# branches to build
branches:
  only:
  - master
  - dev

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cinst 7zip.commandline -x86
  - cd c:\dev\FayeCpp
  - md fayecpp-install-dir
  - git submodule update --init --recursive
#  - cd libwebsockets
#  - git apply < ../libwebsockets_h.patch
#  - cd ../jansson
#  - git apply < ../jansson_msc_1900.patch
#  - cd .. 

build:


build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-dir -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target INSTALL
  - ctest
  - cd c:\dev\FayeCpp\fayecpp-install-dir
  - cmd: 7za a -t7z -mx=9 -xr!cmake -xr!bin -xr!pkgconfig c:\dev\fayecpp.7z c:\dev\FayeCpp\fayecpp-install-dir
  - cd c:\dev

artifacts:
  - path: fayecpp.7z
    name: fayecpp_7z

deploy:
  - provider: GitHub
#   release: fayecpp
    description: 'Appveyor CI build.'
#    auth_token:
#      secure: asdadsadsad
    artifact: fayecpp_7z
    draft: false
    prerelease: true
    on:
      branch: master
