version: 1.5.{build}

# branches to build
branches:
  only:
#  - master
  - dev
  
# Operating system (build VM template)
os: Windows Server 2012

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
#  - x64
#  - AnyCPU

configuration:
#  - Debug
  - Release
  
# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cinst 7zip.commandline -x86
  - cd c:\dev
  - cd c:\dev\FayeCpp
  - git submodule update --init --recursive
  
build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -G"Visual Studio 11" ..
  - dir
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" FayeCpp.sln
  - dir
#  - 7za a -r -t7z c:\dev\release-win32.7z c:\dev\FayeCpp\build
  - cmd: 7za a -r -t7z c:\dev\release-win32.7z c:\dev\FayeCpp\build
  - dir
#  - msbuild /m FayeCpp.sln
  - cd c:\dev


after_build:

test_script:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  # pushing a single file
  - path: *.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  # FTP deployment provider settings
  - provider: FTP
    server: node100.net2ftp.ru
    username: nonamedemail@gmail.com
    password: 699e1f2a44ef
#    folder:
#    application:
    active_mode: false
    enable_ssl: false
