version: 1.5.{build}

# branches to build
branches:
  only:
#  - master
  - dev
  
# Operating system (build VM template)
os: Windows Server 2012

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
#  - x64
#  - AnyCPU

configuration:
#  - Debug
  - Release
  
# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cd c:\dev\FayeCpp
  - git submodule update --init --recursive
  
build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32"
  
  
after_build:

test_script: