version: 0.1.5.{build}

# branches to build
branches:
  only:
  - master
  - dev

# Operating system (build VM template)
os: Windows Server 2012

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86

configuration:
  - Release

# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cinst 7zip.commandline -x86
  - cd c:\dev
  - cd c:\dev\FayeCpp
  - git submodule update --init --recursive

build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - md fayecpp-install-dir
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-dir -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" FayeCpp.sln
  - cmd: cmake --build C:\dev\FayeCpp\build --config RELEASE --target INSTALL
  - cd c:\dev\FayeCpp\fayecpp-install-dir
  - cmd: 7za a -t7z -mx=9 -xr!cmake -xr!pkgconfig -xr!bin c:\dev\%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.7z c:\dev\FayeCpp\fayecpp-install-dir
  - curl --upload-file c:\dev\%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.7z --user b257145@trbvm.com:ff42af47a623 ftp://node100.net2ftp.ru/public_http/fayecpp/


after_build:

test_script:
