version: 1.1.0.{build}


os: Visual Studio 2015


# branches to build
branches:
  only:
  - master
  - dev


# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform:
#  - x86
#  - x64


environment:
  matrix:
    - platform: x86
    - platform: x64


configuration: Release


# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
  - cinst 7zip.commandline -x86
  - cd c:\dev\FayeCpp
  - md fayecpp-install-dir-%PLATFORM%
  - git submodule update --init --recursive
#  - cd libwebsockets
#  - git apply < ../libwebsockets_h.patch
#  - cd ../jansson
#  - git apply < ../jansson_msc_1900.patch
#  - cd .. 


build:


build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-dir-%PLATFORM% -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target INSTALL
  - ctest
  - cd ..


after_build:
  - 7z a -t7z -mx=9 artifacts-%PLATFORM%.7z c:\dev\FayeCpp\fayecpp-install-dir-%PLATFORM%


artifacts:
  - path: artifacts-$(platform).7z


deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: 'Appveyor CI build artifacts'
    auth_token:
      secure: r9lXUEYpmTqZpks3eNZTyWHHka0im0x3NgWpGYSH9uUoWcNatA/cqTGsntk/S5uf
    artifact: artifacts-$(platform).7z
    draft: false
    prerelease: true
    on:
      branch: master
